# Generated by Django 2.2.7 on 2020-02-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('account_number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('nid', models.IntegerField()),
                ('f_name', models.CharField(max_length=50)),
                ('m_name', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'others')], default='M', max_length=1)),
                ('acc_type', models.CharField(choices=[('current', 'current'), ('savings', 'savings')], default='current', max_length=7)),
                ('mobile_no', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('balance', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
