# Generated by Django 2.2.7 on 2020-02-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_statement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='statement',
        ),
    ]
